# Generated by Django 3.2.8 on 2021-10-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='med1',
            field=models.CharField(blank=True, default='OFF', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='med2',
            field=models.CharField(blank=True, default='OFF', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='med3',
            field=models.CharField(blank=True, default='OFF', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='med4',
            field=models.CharField(blank=True, default='OFF', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='med5',
            field=models.CharField(blank=True, default='OFF', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='med6',
            field=models.CharField(blank=True, default='OFF', max_length=3, null=True),
        ),
    ]
